// Generated by CoffeeScript 1.9.3
require.config({
  baseUrl: "./",
  waitSeconds: 0,
  paths: {
    jquery: "vendor/jquery/dist/jquery",
    echarts: "vendor/echarts/build/dist/echarts-all"
  },
  shim: {
    echarts: {
      exports: "echarts"
    }
  }
});

require(['jquery', './js/play'], function(jquery, play) {
  return play.init();
});
