// Generated by CoffeeScript 1.9.3
require.config({
  baseUrl: "./",
  paths: {
    jquery: "vendor/jquery/dist/jquery",
    echarts: "vendor/echarts/build/dist/echarts-all"
  },
  shim: {
    echarts: {
      exports: "echarts"
    }
  }
});
