// Generated by CoffeeScript 1.9.3
define(function(require, exports, module) {
  "use strict";
  var all, map, play;
  require("jquery");
  map = require("module/map");
  all = require("module/all");
  play = {};
  play.init = function() {
    map.init();
    return all.init();
  };
  return module.exports = play;
});
