// Generated by CoffeeScript 1.9.3
define(function(require, exports, module) {
  "use strict";
  var map, play;
  require("jquery");
  map = require("module/map");
  play = {};
  play.init = function() {
    return map.init();
  };
  return module.exports = play;
});
