// Generated by CoffeeScript 1.9.3
define(function(require, exports, module) {
  "use strict";
  var indicator, map, play;
  require("jquery");
  map = require("module/map");
  indicator = require("module/indicator");
  play = {};
  play.init = function() {
    map.init();
    return indicator.init();
  };
  return module.exports = play;
});
