// Generated by CoffeeScript 1.9.3
define(function(require, exports, module) {
  "use strict";
  var all, gChart;
  all = {};
  gChart = require("echarts");
  all.init = function() {
    return all.getData();
  };
  all.getData = function() {
    return $.ajax({
      type: "get",
      url: "./data/country.json",
      dataType: "json",
      success: function(data, status) {
        return all.dataHandle(data);
      }
    });
  };
  all.dataHandle = function(data) {
    var i, item, j, key, keys, len, len1;
    all.allType = {};
    for (i = 0, len = data.length; i < len; i++) {
      item = data[i];
      keys = Object.keys(item);
      for (j = 0, len1 = keys.length; j < len1; j++) {
        key = keys[j];
        all.allType[key] = all.allType[key] || [];
        all.allType[key].push(item[key]);
      }
    }
    return all.dataProcess(all.allType);
  };
  all.dataProcess = function(data) {
    var dataitem, i, index, item, len, obj, ref, series, value;
    value = $("#J-allnav li.active").attr("value").toString();
    series = [];
    item = {
      name: value,
      type: 'map',
      mapType: 'china',
      itemStyle: {
        normal: {
          label: {
            show: true
          }
        },
        emphasis: {
          label: {
            show: true
          }
        }
      },
      data: []
    };
    ref = data[value];
    for (index = i = 0, len = ref.length; i < len; index = ++i) {
      dataitem = ref[index];
      obj = {};
      obj.name = data["position_name"][index];
      obj.value = dataitem;
      item.data.push(obj);
    }
    series.push(item);
    return all.initChart(series);
  };
  all.initChart = function(data) {
    var option;
    console.log(data);
    this.airchart = gChart.init(document.getElementById('airall_chart'));
    option = {
      title: {
        text: '全国气候状况',
        subtext: '数据取自'
      },
      tooltip: {
        trigger: 'item'
      },
      series: data
    };
    return this.airchart.setOption(option);
  };
  return module.exports = all;
});
