// Generated by CoffeeScript 1.9.3
define(function(require, exports, module) {
  "use strict";
  var gChart, indicator;
  gChart = require("echarts");
  indicator = {};
  indicator.init = function() {
    return this.getData();
  };
  indicator.getData = function() {
    return $.ajax({
      type: "get",
      url: "./data/test.json",
      dataType: "json",
      success: function(data, status) {
        return $.ajax({
          type: "get",
          url: "./data/country.json",
          dataType: "json",
          success: function(data, status) {
            return console.log(data);
          }
        });
      }
    });
  };
  return module.exports = indicator;
});
